from typing import Optional, List
from pydantic import BaseModel, Field, field_validator, ConfigDict

class SummarizeRequest(BaseModel):
    content: str = Field(
        ...,
        min_length=10,
        max_length=25000,
        description="Study text material to summarize"
    )
    summary_length: Optional[str] = Field(
        "medium",
        pattern="^(short|medium|detailed)$",
        description="Desired summary length: 'short', 'medium', or 'detailed'"
    )

class SummarizeResponse(BaseModel):
    summary: str = Field(..., description="Concise, clear educational summary")
    key_points: List[str] = Field(default_factory=list, description="Core concepts and bullet points")
    important_terms: List[str] = Field(default_factory=list, description="Key definitions and terminology")

class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Study question to ask the AI assistant"
    )
    context: Optional[str] = Field(
        None,
        max_length=5000,
        description="Optional educational context, course name, or target exam"
    )

    model_config = ConfigDict(extra="forbid")

    @field_validator("question")
    @classmethod
    def validate_question(cls, v: str) -> str:
        trimmed = v.strip()
        if not trimmed:
            raise ValueError("Question cannot be empty or whitespace only.")
        return trimmed

    @field_validator("context")
    @classmethod
    def validate_context(cls, v: Optional[str]) -> Optional[str]:
        if v is not None:
            trimmed = v.strip()
            return trimmed if trimmed else None
        return None

class AskResponse(BaseModel):
    answer: str = Field(..., description="Educational answer generated by AI")
